### ISSUE TITLE
Missing argument validation in Module\Meta::generate()

### ISSUE THREAD

**Issue by dnaber-de** [bordoni/fakerpress#106]
… leads to a fatal error:

```
[Mon Dec 12 10:18:25.123914 2016] [:error] [pid 26975] [client 127.0.0.1:46584] PHP Fatal error:  Uncaught Error: Cannot unset string offsets in /…/fakerpress/modules/meta.php:69
Stack trace:
#0 /…/fakerpress/modules/post.php(178): FakerPress\\Module\\Meta->generate('1', '1', '100')
#1 /var/www/projects/inpsyde/woocommerce/public/wp-content/plugins/fakerpress/inc/class-fp-ajax.php(67): FakerPress\\Module\\Post->parse_request(10, Array)
#2 /…/wp-includes/class-wp-hook.php(298): FakerPress\\Ajax::module_generate('')
#3 /…/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#4 /…/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#5 /…/wp-admin/admin-ajax.php(91): do_action('wp_ajax_fakerpr...')
#6 {main}\n  thrown in /…/fakerpress/modules/meta.php on line 69
```

```PHP
public function generate() {
	// Allow a bunch of params
	$arguments = func_get_args();

	// Remove $key and $name
	$type = array_shift( $arguments );
	$name = array_shift( $arguments );
	$args = array_shift( $arguments );

	$this->data['meta_key'] = null;
	$this->data['meta_value'] = null;

	if ( empty( $type ) ) {
		return $this;
	}

	if ( empty( $name ) ) {
		return $this;
	}

	$this->data['meta_key'] = $name;

	unset( $args['name'], $args['type'] );
	/* … */
}
```
There's no validation of the type of `$args`.

My setup:
WordPress 4.7 Multisite, Fakerpress network activated, Twentysixteen, WooCommerce activated on a site.

The error occurs with the following settings on the AJAX request when clicking »Generate«:

![fakerpress](https://cloud.githubusercontent.com/assets/1133205/21094444/58157dba-c057-11e6-9054-9eecf2445c88.png)

**Comment by fbm-static** [comment]
I'm experiencing this as well to generate woocommerce products.

**Comment by bordoni** [comment]
Thanks to @Mte90, this shouldn't be a bug anymore on `0.4.8`
